dist: trusty
group: travis_latest
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  fast_finish: true

  include:
    - python: "2.7"
      env: TOXENV=py27-pyopenssl015-idna
    - python: "2.7"
      env: TOXENV=py27-pyopenssl014-idna
    - python: "2.7"
      env: TOXENV=py27-pyopensslLatest-idna
    - python: "2.7"
      env: TOXENV=py27-pyopensslLatest-noidna
    - python: "3.4"
      env: TOXENV=py34-pyopenssl015-idna
    - python: "3.4"
      env: TOXENV=py34-pyopenssl014-idna
    - python: "3.4"
      env: TOXENV=py34-pyopensslLatest-idna
    - python: "3.5"
      env: TOXENV=py35-pyopenssl015-idna
    - python: "3.5"
      env: TOXENV=py35-pyopenssl014-idna
    - python: "3.5"
      env: TOXENV=py35-pyopensslLatest-idna
    - python: "3.6"
      env: TOXENV=py36-pyopenssl015-idna
    - python: "3.6"
      env: TOXENV=py36-pyopenssl014-idna
    - python: "3.6"
      env: TOXENV=py36-pyopensslLatest-idna
    - python: "3.6"
      env: TOXENV=py36-pyopensslLatest-noidna
    - python: "pypy"
      env: TOXENV=pypy-pyopenssl015-idna
    - python: "pypy"
      env: TOXENV=pypy-pyopenssl014-idna
    - python: "pypy"
      env: TOXENV=pypy-pyopensslLatest-idna
    - python: "pypy3"
      env: TOXENV=pypy3-pyopenssl015-idna
    - python: "pypy3"
      env: TOXENV=pypy3-pyopenssl014-idna
    - python: "pypy3"
      env: TOXENV=pypy3-pyopensslLatest-idna

    # Prevent breakage by a new releases
    - python: "3.6-dev"
      env: TOXENV=py36-pyopensslLatest-idna
    - python: "3.7-dev"
      env: TOXENV=py37-pyopensslLatest-idna

    # Meta
    - python: "3.6"
      env: TOXENV=flake8
    - python: "3.6"
      env: TOXENV=manifest
    - python: "3.6"
      env: TOXENV=docs
    - python: "3.6"
      env: TOXENV=readme

  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"


install:
  - pip install -U tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
